/**
 *This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
 *Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
 */

package
{
	import flash.display.Sprite;
	
	import tests.MainSuite;
	import tests.CardsImagesLoaderTest;
	import tests.CardsGeneratorTest;
	import tests.SimpleCardsPlacerTest;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		private var tests_SimpleCardsPlacerTest_obj:tests.SimpleCardsPlacerTest;
		private var tests_CardGeneratorTest_obj:tests.CardsGeneratorTest;
		private var tests_CardsImagesLoaderTest_obj:tests.CardsImagesLoaderTest;
		
		private var tests_MainSuite_obj:tests.MainSuite;
	}
}