/**
*This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
*Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
*/

package
{
	import flash.display.Sprite;
	
	import tests.CardTest;
	import tests.CardsGeneratorTest;
	import tests.CardsImagesLoaderTest;
	import tests.SimpleCardsPlacerTest;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		
		private var tests_SimpleCardsPlacerTest_obj:tests.SimpleCardsPlacerTest;
		private var tests_CardTest_obj:tests.CardTest;
		private var tests_CardsImagesLoaderTest_obj:tests.CardsImagesLoaderTest;
		private var tests_CardsGeneratorTest_obj:tests.CardsGeneratorTest;
	}
}